### ISSUE TITLE
JSON over YAML for index and layers

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha-dev/openpecha-toolkit#71]
# Comparison

YAML is human-friendly therefore, great for manual editing but it's slow.
JSON is not human-friendly but [much faster than YAML](https://stackoverflow.com/questions/27743711/can-i-speedup-yaml) for both loading and dumping.

# Our use case
- We are facing a very slow loading of index.yml for katen pechas at the moment.
- There is no limit to the size of index.yml and layers.yml files. This will lead to very slow loading and dumping for large layers files.
- Index and layers are not intended for manual editing therefore, I propose to use JSON over YAML for index and layers.

TODO:
- [ ] convert all the index.yml and <layers>.yml to .json with cli
- [ ] Load and dump json in formatters
- [ ] Load json in serializer.

@eroux @ngawangtrinley @kaldan007

**Comment by eroux** [comment]
can you give some figures of comparison please? This is a pretty radical and costly change so let's think it through first. Also did you try the yaml `CLoader` as indicated in the link you point to? It would be good to take a big OP and understand what operation you're making that is very slow and how to speed it up. This might lead to the identification of a different bottleneck

**Comment by 10zinten** [comment]
sure, I will do a bench mark comparison between  them with CLoader and CDumper.

**Comment by eroux** [comment]
thanks! having a real world use case will be interesting too, as there might be other bottlenecks for this use case

**Comment by eroux** [comment]
@10zinten is the new yaml reader / serializer satisfactory?

**Comment by 10zinten** [comment]
yes, @kaldan007 has tested on that and the results were satisfactory.
